name: Compile C++ Binary

on:
  workflow_dispatch:
    inputs:
      binary_name:
        description: 'Name for the final binary file (e.g., jm or TerrariaServer.bin.x86_64)'
        required: true
        default: 'jm'
      chmod_permissions:
        description: 'Permissions for the binary (e.g., 777 or 755)'
        required: true
        default: '777'
      source_code:
        description: 'The C++ code to compile.'
        required: true
        type: string
        default: |
          #include <iostream>
          int main() {
              std::cout << "This is a\n";
              std::cout << "multi-line\n";
              std::cout << "message.\n";
              return 0;
          }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang compiler
        run: sudo apt-get update && sudo apt-get install -y clang

      - name: Write source code to file
        run: echo "${{ github.event.inputs.source_code }}" > source.cpp

      - name: Compile C++ code into a static binary
        run: clang++ -static source.cpp -o "${{ github.event.inputs.binary_name }}"

      - name: Set permissions for the binary
        run: chmod ${{ github.event.inputs.chmod_permissions }} "${{ github.event.inputs.binary_name }}"

      - name: Upload the binary as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.binary_name }}
          path: ${{ github.event.inputs.binary_name }}
