name: Compile and Commit Plugins

on:
  workflow_dispatch:
    inputs:
      plugin_folders:
        description: 'Space-separated paths to plugin source directories.'
        required: true
        type: string
        default: 'Replenisher-main/Replenisher/ EssentialsPlus-Anz-Changes/EssentialsPlus/'
      output_directory:
        description: 'Directory to place the final compiled plugins.'
        required: true
        type: string
        default: 'ServerPlugins'
      commit_message:
        description: 'The commit message for the compiled plugins.'
        required: true
        type: string
        default: 'build: Compile plugins from source'

jobs:
  compile-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.428'

      - name: Clean and Prepare Output Directory
        run: |
          echo "Cleaning and preparing the output directory: ${{ github.event.inputs.output_directory }}"
          rm -rf ${{ github.event.inputs.output_directory }}
          mkdir -p ${{ github.event.inputs.output_directory }}

      - name: Compile Plugins and Collect Output
        run: |
          for folder in ${{ github.event.inputs.plugin_folders }}; do
            if [ -z "$folder" ]; then continue; fi

            echo "--- Processing folder: $folder ---"
            if [ ! -d "$folder" ]; then
              echo "⚠️ Warning: Folder '$folder' not found. Skipping."
              continue
            fi
            
            csproj_file=$(find "$folder" -maxdepth 1 -type f -name "*.csproj" -print -quit)
            
            if [ -z "$csproj_file" ]; then
              echo "❌ Error: No .csproj file found directly in '$folder'. Skipping."
              continue
            fi
            
            echo "Building project: $csproj_file"
            # Added -p:PlatformTarget=x64 to resolve architecture mismatch warnings (MSB3270)
            dotnet build "$csproj_file" --configuration Release -p:PlatformTarget=x64
            
            # This is the corrected path detection logic
            build_config="Release"
            target_framework="net6.0" # Based on the project files
            # First, check for the custom <OutputPath>
            output_source_path="$(dirname "$csproj_file")/bin/$build_config/ServerPlugins"
            # If that doesn't exist, fall back to the default path
            if [ ! -d "$output_source_path" ]; then
              output_source_path="$(dirname "$csproj_file")/bin/$build_config/$target_framework"
            fi
            
            if [ -d "$output_source_path" ]; then
              echo "Collecting files from: $output_source_path"
              # Copy all files from the plugin's output to our final directory
              cp -r "$output_source_path"/* "${{ github.event.inputs.output_directory }}/"
            else
              echo "❌ Error: Could not find compiled output in standard paths for '$folder'."
              exit 1
            fi
          done

      - name: Commit and Push Compiled Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add ${{ github.event.inputs.output_directory }}
          
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing..."
            git commit -m "${{ github.event.inputs.commit_message }}"
            git push
          else
            echo "No changes detected, nothing to commit."
          fi
