name: Compile and Commit Plugins

on:
  workflow_dispatch:
    inputs:
      plugin_folders:
        description: 'Space-separated paths to plugin source directories.'
        required: true
        type: string
        default: 'Replenisher-main/Replenisher/ EssentialsPlus-Anz-Changes/EssentialsPlus/'
      output_directory:
        description: 'Directory to place the final compiled plugins.'
        required: true
        type: string
        default: 'ServerPlugins'
      commit_message:
        description: 'The commit message for the compiled plugins.'
        required: true
        type: string
        default: 'build: Compile plugins from source'

jobs:
  compile-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.428'

      - name: Clean Output Directory
        run: |
          echo "Cleaning up the output directory before build..."
          rm -rf ${{ github.event.inputs.output_directory }}
          mkdir -p ${{ github.event.inputs.output_directory }}

      - name: Compile Plugins and Collect Output
        run: |
          # Robustly parse the space-separated input string into an array.
          readarray -d $'\0' folders < <(printf '%s\0' "${{ github.event.inputs.plugin_folders }}" | xargs -0 -n 1 printf '%s\0')
          
          for folder in "${folders[@]}"; do
            if [ -z "$folder" ]; then continue; fi

            echo "--- Processing folder: $folder ---"
            if [ ! -d "$folder" ]; then
              echo "⚠️ Warning: Folder '$folder' not found. Skipping."
              continue
            fi
            
            # Find the .csproj file within the specified folder
            csproj_file=$(find "$folder" -maxdepth 1 -type f -name "*.csproj" -print -quit)
            
            if [ -z "$csproj_file" ]; then
              echo "❌ Error: No .csproj file found directly in '$folder'. Skipping."
              continue
            fi
            
            echo "Building project: $csproj_file"
            dotnet build "$csproj_file" --configuration Release
            
            # This is the corrected path that respects the <OutputPath> in the .csproj files
            output_source_path="$(dirname "$csproj_file")/bin/Release/ServerPlugins"
            
            if [ -d "$output_source_path" ]; then
              echo "Collecting DLLs from: $output_source_path"
          
              cp "$output_source_path"/* "${{ github.event.inputs.output_directory }}/"
            else
              echo "⚠️ Warning: Compiled output directory '$output_source_path' not found. No DLLs collected for '$folder'."
            fi
          done

      - name: Commit and Push Compiled Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the entire output directory
          git add ${{ github.event.inputs.output_directory }}
          
          # Check if there are any changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing..."
            git commit -m "${{ github.event.inputs.commit_message }}"
            git push
          else
            echo "No changes detected, nothing to commit."
          fi
