name: Simple Documentation Generator
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Unpack Archive
        run: |
          unzip -o claude-code-router-main.zip

      - name: Consolidate All Readable Files
        run: |
          OUTPUT_FILE="claude_documentation.md"
          SOURCE_DIR="claude-code-router-main"
          
          echo "# Documentation for ${SOURCE_DIR}" > $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE

          # This simple and reliable find command will get every file
          find "$SOURCE_DIR" -type f | sort | while read -r file; do
            
            # This check correctly identifies any text/code file and ignores binaries
            if file -b --mime-type "$file" | grep -q "text"; then
              echo "Processing: $file"
              echo "---" >> $OUTPUT_FILE
              echo "## File: \`$file\`" >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
              echo '```' >> $OUTPUT_FILE
              cat "$file" >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
              echo '```' >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
            else
              echo "Skipping binary file: $file"
            fi
          done

      - name: Commit Documentation File
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add claude_documentation.md
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "docs: Generate documentation for claude-code-router"
            git push
          else
            echo "No changes to the documentation file."
          fi
