name: Create Structured Project Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install tree utility for file ordering
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate organized documentation
        run: |
          OUTPUT_FILE="consolidated_documentation.md"
          
          echo "# Project Documentation" > $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE

          if [ -f "readme.md" ]; then
            echo "## 1. README" >> $OUTPUT_FILE
            echo '```markdown' >> $OUTPUT_FILE
            cat readme.md >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
            echo '```' >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
          fi

          if [ -f "design.md" ]; then
            echo "## 2. Design Document" >> $OUTPUT_FILE
            echo '```markdown' >> $OUTPUT_FILE
            cat design.md >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
            echo '```' >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
          fi

          echo "## 3. Project File Tree" >> $OUTPUT_FILE
          echo '```' >> $OUTPUT_FILE
          tree -I ".git|.github|${OUTPUT_FILE}" >> $OUTPUT_FILE
          echo '```' >> $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE

          echo "## 4. Source Files" >> $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE
          
          current_dir=""
          EXCLUSIONS="-I .git -I .github -I ${OUTPUT_FILE} -I readme.md -I design.md"

          tree -if --noreport $EXCLUSIONS | while read -r file; do
            if [ ! -f "$file" ]; then continue; fi

            if file -b --mime-type "$file" | grep -q "text"; then
              file_dir=$(dirname "$file")
              if [ "$file_dir" != "$current_dir" ]; then
                current_dir="$file_dir"
                echo "### Folder: \`$current_dir\`" >> $OUTPUT_FILE
                echo "" >> $OUTPUT_FILE
              fi
              
              echo "#### File: \`$file\`" >> $OUTPUT_FILE
              echo '```' >> $OUTPUT_FILE
              cat "$file" >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
              echo '```' >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
            fi
          done

      - name: Commit and push documentation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add consolidated_documentation.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "docs: Generate structured project documentation"
            git push
          else
            echo "No changes to commit."
          fi
