name: Create Organized Project View
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  consolidate-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install tree utility
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Consolidate files in order
        run: |
          OUTPUT_FILE="consolidated_project.md"

          # 1. Start with the main title
          echo "# Consolidated Project Documentation" > $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE

          # 2. Append README.md if it exists
          if [ -f "readme.md" ]; then
            echo "---" >> $OUTPUT_FILE
            echo "## 1. Main README" >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
            echo '```markdown' >> $OUTPUT_FILE
            cat readme.md >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
            echo '```' >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
          fi

          # 3. Append design.md if it exists
          if [ -f "design.md" ]; then
            echo "---" >> $OUTPUT_FILE
            echo "## 2. Design Document" >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
            echo '```markdown' >> $OUTPUT_FILE
            cat design.md >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
            echo '```' >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
          fi

          # 4. Generate and append the file tree
          echo "---" >> $OUTPUT_FILE
          echo "## 3. Project File Tree" >> $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE
          echo '```' >> $OUTPUT_FILE
          tree -I ".git|.github|${OUTPUT_FILE}" >> $OUTPUT_FILE
          echo '```' >> $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE

          # 5. Append all other text files, sorted for consistency
          echo "---" >> $OUTPUT_FILE
          echo "## 4. Source Files" >> $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -not -name "$OUTPUT_FILE" -not -name "readme.md" -not -name "design.md" | sort | while read -r file; do
            if file -b --mime-type "$file" | grep -q "text"; then
              echo "### File: \`$file\`" >> $OUTPUT_FILE
              echo '```' >> $OUTPUT_FILE
              cat "$file" >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
              echo '```' >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
            fi
          done

      - name: Commit and push the consolidated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add consolidated_project.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "docs: Update organized project documentation"
            git push
          else
            echo "No changes to the consolidated project file."
          fi
