name: Unpack and Commit
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Unpack and Move Contents
        run: |
          unzip -o "terra-awg-main (3).zip"
          rsync -a terra-awg-main/ .
          rm -rf terra-awg-main
          rm "terra-awg-main (3).zip"

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated commit: Unpack and move files"
            git push
          else
            echo "No changes to commit."
          fi
