name: Run Terra-AWG Live

on:
  workflow_dispatch:

jobs:
  run-program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Terra-AWG
        run: |
          chmod +x Terra/terra-awg
          ./Terra/terra-awg
