name: TerraAWG Runner
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'World Name (use RANDOM for a random name)'
        required: true
        type: string
        default: 'Terra AWG World'
      seed:
        description: 'World Seed (use RANDOM for a random seed)'
        required: true
        type: string
        default: 'RANDOM'
      size:
        description: 'Select a world size'
        required: true
        type: choice
        options:
        - Extra Small
        - Small
        - Medium
        - Large
        - Extra Large
        default: 'Medium'
      evil_and_world_type:
        description: 'Select the evil biome or a special world type'
        required: true
        type: choice
        options:
        - RANDOM
        - corruption
        - crimson
        - Both (Drunk World)
        - Disabled (Purity)
        default: 'RANDOM'
      hardmode_options:
        description: 'Select a Hardmode option'
        required: true
        type: choice
        options:
        - Disabled
        - Enabled
        - Enabled (with Hardmode Loot)
        default: 'Disabled'
      starter_options:
        description: 'Select starter home and equipment options'
        required: true
        type: choice
        options:
        - No
        - Yes (Home Only)
        - Yes (Home + Iron Gear)
        default: 'No'

jobs:
  generate-world:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate config file from inputs
        shell: pwsh
        run: |
          $width = 6400; $height = 1800
          switch ("${{ github.event.inputs.size }}") {
            "Extra Small" { $width = 2100; $height = 600 }
            "Small"       { $width = 4200; $height = 1200 }
            "Medium"      { $width = 6400; $height = 1800 }
            "Large"       { $width = 8400; $height = 2400 }
            "Extra Large" { $width = 12600; $height = 3600 }
          }

          $hardmode = "false"; $hardmodeLoot = "false"
          switch ("${{ github.event.inputs.hardmode_options }}") {
            "Enabled" { $hardmode = "true" }
            "Enabled (with Hardmode Loot)" { $hardmode = "true"; $hardmodeLoot = "true" }
          }
          
          $evil = "RANDOM"; $doubleTrouble = "false"; $purity = "false"
          switch ("${{ github.event.inputs.evil_and_world_type }}") {
            "corruption" { $evil = "corruption" }
            "crimson"    { $evil = "crimson" }
            "Both (Drunk World)" { $doubleTrouble = "true" }
            "Disabled (Purity)"  { $purity = "true" }
          }

          $home = "false"; $equipment = "none"
          switch ("${{ github.event.inputs.starter_options }}") {
            "Yes (Home Only)"        { $home = "true" }
            "Yes (Home + Iron Gear)" { $home = "true"; $equipment = "iron" }
          }

          $iniContent = @"
          [world]
          name = ${{ github.event.inputs.name }}
          seed = ${{ github.event.inputs.seed }}
          width = $width
          height = $height
          mode = classic
          evil = $evil
          home = $home
          [variation]
          equipment = $equipment
          doubleTrouble = $doubleTrouble
          purity = $purity
          hardmode = $hardmode
          hardmodeLoot = $hardmodeLoot
          [extra]
          map = true
          "@
          Set-Content -Path "Terra/terra-awg.ini" -Value $iniContent
          Get-Content -Path "Terra/terra-awg.ini"

      - name: Run World Generator
        shell: pwsh
        run: |
          cd Terra
          ./terra-awg.exe
          cd ..
      
      - name: Upload Generated Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-world-files
          path: |
            Terra/*.wld
            Terra/*.png
          if-no-files-found: error
