name: TerraAWG Runner
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'World Name (use RANDOM for a random name)'
        required: true
        type: string
        default: 'Terra AWG World'
      seed:
        description: 'World Seed (use RANDOM for a random seed)'
        required: true
        type: string
        default: 'RANDOM'
      width:
        description: 'World Width (e.g., 4200, 6400, 8400)'
        required: true
        type: number
        default: 6400
      height:
        description: 'World Height (e.g., 1200, 1800, 2400)'
        required: true
        type: number
        default: 1800
      mode:
        description: 'Difficulty'
        required: true
        type: choice
        options: [classic, expert, master, journey]
        default: 'classic'
      evil:
        description: 'World Evil'
        required: true
        type: choice
        options: [RANDOM, corruption, crimson]
        default: 'RANDOM'
      frequency_multiplier:
        description: 'MASTER MULTIPLIER for all frequencies (ore, chests, gems, etc.)'
        required: true
        type: number
        default: 1.0
      size_multiplier:
        description: 'MASTER MULTIPLIER for all sizes (dungeon, temple, evil, etc.)'
        required: true
        type: number
        default: 1.0
      home:
        description: 'Add a starter home at spawn?'
        required: true
        type: boolean
        default: false
      equipment:
        description: 'Add starter equipment at spawn?'
        required: true
        type: choice
        options: [none, iron, platinum, hellstone, mythril]
        default: 'none'
      doubleTrouble:
        description: 'Drunk World (both evils, all ores)'
        required: true
        type: boolean
        default: false
      hardmode:
        description: 'Start in Hardmode'
        required: true
        type: boolean
        default: false
      forTheWorthy:
        description: 'For The Worthy secret seed effects'
        required: true
        type: boolean
        default: false
      map:
        description: 'Output a .png map preview image?'
        required: true
        type: boolean
        default: true

jobs:
  generate-world:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate config file from inputs
        shell: pwsh
        run: |
          $iniContent = @"
          [world]
          name = ${{ github.event.inputs.name }}
          seed = ${{ github.event.inputs.seed }}
          width = ${{ github.event.inputs.width }}
          height = ${{ github.event.inputs.height }}
          mode = ${{ github.event.inputs.mode }}
          evil = ${{ github.event.inputs.evil }}
          home = ${{ github.event.inputs.home }}
          [variation]
          equipment = ${{ github.event.inputs.equipment }}
          doubleTrouble = ${{ github.event.inputs.doubleTrouble }}
          hardmode = ${{ github.event.inputs.hardmode }}
          forTheWorthy = ${{ github.event.inputs.forTheWorthy }}
          ore = ${{ github.event.inputs.frequency_multiplier }}
          lifeCrystals = ${{ github.event.inputs.frequency_multiplier }}
          manaCrystals = ${{ github.event.inputs.frequency_multiplier }}
          pots = ${{ github.event.inputs.frequency_multiplier }}
          chests = ${{ github.event.inputs.frequency_multiplier }}
          gems = ${{ github.event.inputs.frequency_multiplier }}
          traps = ${{ github.event.inputs.frequency_multiplier }}
          trees = ${{ github.event.inputs.frequency_multiplier }}
          livingTrees = ${{ github.event.inputs.frequency_multiplier }}
          clouds = ${{ github.event.inputs.frequency_multiplier }}
          asteroids = ${{ github.event.inputs.frequency_multiplier }}
          minecartTracks = ${{ github.event.inputs.frequency_multiplier }}
          marbleFreq = ${{ github.event.inputs.frequency_multiplier }}
          graniteFreq = ${{ github.event.inputs.frequency_multiplier }}
          glowingMushroomFreq = ${{ github.event.inputs.frequency_multiplier }}
          hiveFreq = ${{ github.event.inputs.frequency_multiplier }}
          spiderNestFreq = ${{ github.event.inputs.frequency_multiplier }}
          glowingMossFreq = ${{ github.event.inputs.frequency_multiplier }}
          dungeonSize = ${{ github.event.inputs.size_multiplier }}
          templeSize = ${{ github.event.inputs.size_multiplier }}
          evilSize = ${{ github.event.inputs.size_multiplier }}
          oceanSize = ${{ github.event.inputs.size_multiplier }}
          oceanCaveSize = ${{ github.event.inputs.size_multiplier }}
          marbleSize = ${{ github.event.inputs.size_multiplier }}
          graniteSize = ${{ github.event.inputs.size_multiplier }}
          glowingMushroomSize = ${{ github.event.inputs.size_multiplier }}
          hiveSize = ${{ github.event.inputs.size_multiplier }}
          spiderNestSize = ${{ github.event.inputs.size_multiplier }}
          glowingMossSize = ${{ github.event.inputs.size_multiplier }}
          snowSize = ${{ github.event.inputs.size_multiplier }}
          desertSize = ${{ github.event.inputs.size_multiplier }}
          jungleSize = ${{ github.event.inputs.size_multiplier }}
          aetherSize = ${{ github.event.inputs.size_multiplier }}
          [extra]
          map = ${{ github.event.inputs.map }}
          "@
          Set-Content -Path "Terra/terra-awg.ini" -Value $iniContent
          echo "--- terra-awg.ini created ---"
          Get-Content -Path "Terra/terra-awg.ini"

      - name: Run World Generator
        shell: pwsh
        run: |
          cd Terra
          echo "--- Running Terra AWG ---"
          ./terra-awg.exe
          echo "--- World generation complete. ---"
          cd ..
      
      - name: Upload Generated Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-world-files
          path: |
            Terra/*.wld
            Terra/*.png
          if-no-files-found: error
